### ISSUE TITLE
Argument #2 ($responseToken) must be of type string, null given

### ISSUE THREAD

**Issue by CNRP** [larswolters98/laravel-recaptcha-v3#2]
Hey, So I'm getting the following error 

`
Larswolters98\LaravelRecaptchaV3\Services\RecaptchaService::__construct(): Argument #2 ($responseToken) must be of type string, null given, called in D:\DOCKER\connor-price-store\vendor\larswolters98\laravel-recaptcha-v3\src\Recaptcha.php on line 40
`

`
40:        if (Recaptcha::check()->fails()) {
            return redirect()->back()->with('status', 'recaptcha-failed');
        }
`
I've added with composer, added the uselarswolters98/laravelrecapatchav3 facade in the controller & added my secret key

I'm guessing I've missed steps in configuring this.. but I'm not too sure as I'm pretty new to how reCAPTCHA works.. any help would be very much appreciated.

**Comment by larswolters98** [comment]
Hi @CNRP,

Did you publish the config file by running:

`php artisan vendor:publish --provider="Larswolters98\LaravelRecaptchaV3\RecaptchaServiceProvider"`

**Comment by CNRP** [comment]
Appreciate you getting back to me.
I have indeed. In terms of the google side, other than obtaining the secret key etc, Do I have to add anything else to the content of the website to facilitate this working that I may have missed? 

I am testing on a local environment, however have also set this in the hosts for the reCAPATCHA admin console.

**Comment by larswolters98** [comment]
@CNRP Did you setup the client side (https://developers.google.com/recaptcha/docs/v3)?

**Comment by CNRP** [comment]
I have done step1, which does seem to have worked as it now appears bottom right, however with step 2 I'm not exactly sure where I'm supposed to implement this, do I add this functionality to run whenever a form button is clicked? 

I'm guessing I need to figure out how to send this token back with the response then, I assumed it might be handled automatically. Thanks for the help with this, apologise if my questions are a bit dumb this is the first time I've had to configure anything like this.

**Comment by larswolters98** [comment]
@CNRP Yes, you can do it through a form button OR programmatically invoke the challenge (as shown in the screenshot above).
